name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t leena051100/pythonApp .

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

    - name: Push Docker image
      run: docker push leena051100/pythonApp
